version: "3.9"

services:
  backend:
    build:
      context: ./src
      dockerfile: Dockerfile

    env_file:
      - ./src/.env

    restart: always

    ports:
      - "8000:8000"

    depends_on:
      - postgres_db


  postgres_db:
    image: postgres:14.8-alpine3.18
    volumes:
      - postgres_db:/var/lib/postgresql/data
    env_file:
      - ./src/.env
    restart: always

    ports:
      - "5433:5432"


volumes:
  postgres_db: